stages:
  clean:
    cmd: poetry run python src/clean.py
    deps:
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Records_TRAIN.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Representations_TRAIN.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Consumptions_TRAIN.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Requests_TRAIN.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/PowerThefts_TRAIN.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Records_TEST.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Representations_TEST.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Consumptions_TEST.csv
    - /content/drive/MyDrive/DEDDIE_Datathon/Data/Requests_TEST.csv
    outs:
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Records_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Representations_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Consumptions_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Requests_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/PowerThefts_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Records_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Representations_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Consumptions_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Requests_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/ACCT_NBR_label_encoder.pkl

  preprocessing:
    cmd: poetry run python src/preprocessing.py
    deps:
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Records_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Representations_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Consumptions_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Requests_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/PowerThefts_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Records_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Representations_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Consumptions_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/1.cleaned_data/Requests_TEST.pqt
    outs:
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Records_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Consumptions_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Requests_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/PowerThefts_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Records_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Consumptions_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Requests_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/3.pivoted_data/test_users.pqt

  pivot:
    cmd: poetry run python src/pivot.py
    deps:
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Consumptions_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Consumptions_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Requests_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Requests_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Records_TRAIN.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/Records_TEST.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/2.preprocessed_data/PowerThefts_TRAIN.pqt
    outs:
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/3.pivoted_data/data.pqt
  
  featurize:
    cmd: poetry run python src/featurize.py
    deps:
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/3.pivoted_data/data.pqt
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/3.pivoted_data/test_users.pqt
    outs:
    - /content/drive/MyDrive/DEDDIE_Datathon/npavin_data/4.ready_to_use_data/data.pqt